### PR TITLE
utils: trace: Wait for given initial state after creating the trace.

### LINKED ISSUE #391: [RFE] Report gadget errors immediately without waiting until it is stopped
## Current situation

Consider the following situation with the biolatency gadget but it applies to all the gadgets. 

Given that the biolatency gadget does not support any kind of filtering, it reports an error and does not even start if the Spec.Filter field is present in the trace:

```
$ cat <<EOF | kubectl apply -f -
> apiVersion: gadget.kinvolk.io/v1alpha1
> kind: Trace
> metadata:
>   name: biolatency
>   namespace: gadget
> spec:
>   node: worker
>   gadget: biolatency
>   filter:
>     namespace: demo
>   runMode: Manual
>   outputMode: Status
> EOF
trace.gadget.kinvolk.io/biolatency created

$ kubectl annotate -n gadget trace biolatency gadget.kinvolk.io/operation=start
trace.gadget.kinvolk.io/biolatency annotated

$ kubectl get -n gadget trace biolatency -o jsonpath='{.status}'
{"operationError":"Invalid filter: Filtering is not supported"}
```

However, using the CLI, the error will be shown to the user only when the gadget is stopped even if the error is already present in the trace: 
```
$ ./kubectl-gadget biolatency start --node worker -n example-namespace
pkmVNFBDj6KeB4D0

# The user thinks the gadget is correctly running when it did not even start
$ kubectl get traces -n gadget
NAME               AGE
biolatency-flsfm   8s
$ kubectl get -n gadget trace biolatency-flsfm -o jsonpath='{.status}'
{"operationError":"Invalid filter: Filtering is not supported"}

# The user believes the gadget is running and collecting information because the errors are shown only when the gadget is stopped
$ ./kubectl-gadget biolatency stop pkmVNFBDj6KeB4D0
Failed to run the gadget on node "worker": Invalid filter: Filtering is not supported
Error: failure printing the trace output: Failed to run the gadget on all nodes: None of them succeeded
```

## Impact

The user wastes time thinking that things go well because the errors are shown only when the gadget is stopped.

## Ideal future situation

It is not necessary to wait until the gadget is stopped to show the errors. 

## **Implementation options

My proposal is to call `waitForOutput` (which can be called `waitForStatus` and would probably need some changes) after having created the trace, to ensure that it moved to `Started` and it does not carry any error/warning. 

## Additional information

Of course this could be solved by adding some check on the CLI but it does not make sense to write twice (On the CLi and on the gadget side) the same validation.

### PR DESCRIPTION
**Pull request by eiffel-fl**
Hi.

In this commit, I added waiting for the trace to be in a given by user initial state once it is created.
The advantage of doing so is that we give a "ready to use" trace to the user and also print trace warnings and errors during its creation rather than waiting for the user to use a `stop` operation.

It fixes #391.

Best regards.

### CODE REVIEW

File: cmd/kubectl-gadget/dns.go [hunk 1]
```diff
@@ -64,11 +64,12 @@ var dnsCmd = &cobra.Command{
...
-			GadgetName:       "dns",
-			Operation:        "start",
-			TraceOutputMode:  "Stream",
-			TraceOutputState: "Started",
-			CommonFlags:      &params,
+			GadgetName:        "dns",
+			Operation:         "start",
+			TraceOutputMode:   "Stream",
+			TraceOutputState:  "Started",
+			TraceInitialState: "Started",
```
Comment (blanquicet) [inline cmd/kubectl-gadget/dns.go:71]: I think it is useful for the DNS gadget to use this new feature. It will wait twice for the same status in a single CLI call.

File: cmd/kubectl-gadget/utils/trace.go [hunk 2]
```diff
@@ -68,6 +68,11 @@ type TraceConfig struct {
 	// But other gadgets, like dns, can contain output only in Started state.
 	TraceOutputState string
 
+	// TraceInitialState is the state in which the trace should be after its
+	// creation.
+	// This field is not used by *-collector gadget but needed by others.
+	TraceInitialState string
+
```
Comment (blanquicet) [inline cmd/kubectl-gadget/utils/trace.go:75]: As per my previous comment. I think this feature should be used only for multi-round gadgets. I don't think it makes sense for gadgets that make everything in a single CLI call and uses `RunTraceAndPrint*` functions.

File: cmd/kubectl-gadget/utils/trace.go [hunk 3]
```diff
@@ -314,6 +319,15 @@ func CreateTrace(config *TraceConfig) (string, error) {
 		return "", err
 	}
 
+	if config.TraceInitialState != "" {
+		// Once the traces are created, we wait for them to be in "Started" state,
+		// so they are ready to be used by the user.
+		_, err = waitForTraceInState(traceID, config.TraceInitialState)
+		if err != nil {
+			return "", err
+		}
```
Comment (blanquicet) [inline cmd/kubectl-gadget/utils/trace.go:328]: Mmmm I think we need to delete the trace in case of an error. Otherwise, the API is reporting an error but the trace is still there.

If you decide to handle this scenario in this way, please update the function description to explain that if `TraceInitialState` is specified, then this function will succeed only if the trace is correctly created and it goes into the requested state.

File: cmd/kubectl-gadget/utils/trace.go [hunk 4]
```diff
@@ -379,11 +393,9 @@ func SetTraceOperation(traceID string, operation string) error {
...
 }
 
-// waitForOutput loops over all trace whom ID is given as parameter waiting
-// until they are in the expected state.
-// After this function and if correct state was given as parameter, the trace
-// output should contain the needed information.
-func waitForOutput(traceID string, expectedState string) (gadgetv1alpha1.TraceList, error) {
+// waitForTraceInState loops over all trace whom ID is given as parameter
+// waiting until they are in the expected state.
+func waitForTraceInState(traceID string, expectedState string) (gadgetv1alpha1.TraceList, error) {
```
Comment (blanquicet) [inline cmd/kubectl-gadget/utils/trace.go:398]: Does the name `waitForTraceInState` come from "wait for trace initial state"?

IMO, `waitForTraceState` would be more appropriate given that it could wait for both `Initial` and `Output` states. WDYT?

**Review by blanquicet — COMMENTED** [review]
Thanks @eiffel-fl for working on this!

It looks good. I tested it using the biolatency gadget and it worked as expected except that the trace wasn't deleted.

File: cmd/kubectl-gadget/utils/trace.go (hunk 4 above)
Comment (eiffel-fl) [reply cmd/kubectl-gadget/utils/trace.go:398]: `waitForTraceInState` was for "wait for trace in state".
But I agree with your suggestion.

**Review by blanquicet — APPROVED** [review]
Tested using the biolatency gadget and LGTM!

File: cmd/kubectl-gadget/utils/trace.go [hunk 5]
```diff
@@ -314,6 +321,21 @@ func CreateTrace(config *TraceConfig) (string, error) {
 		return "", err
 	}
 
+	if config.TraceInitialState != "" {
+		// Once the traces are created, we wait for them to be in "Started" state,
```
Comment (mauriciovasquezbernal) [inline cmd/kubectl-gadget/utils/trace.go:325]:
```suggestion
		// Once the traces are created, we wait for them to be in config.TraceInitialState state,
```

**Review by mauriciovasquezbernal — APPROVED** [review]
LGTM!
