### PR TITLE
utils: trace: Fix traces number increasing in waitForCondition().

### LINKED ISSUE #525: `waitForTraceState()` returns before dealing with all trace with the given ID
https://kubernetes.slack.com/archives/CSYL75LF6/p1645443664396869 -> 

--- Slack message: 

Hi!  the watch api (https://github.com/kinvolk/inspektor-gadget/pull/398) does not seem to work on a 3 nodes clusters. I needed to add the following as a workaround:
https://gist.github.com/alban/2d5861aa0aad42b39bd204e066a5c681
Otherwise, it stops at the first "Added" event for the first node, and stops processing the following events.

### PR DESCRIPTION
**Pull request by eiffel-fl**
Hi.

This PR removes the computing of total traces number from `waitForCondition()`.
So, it fixes #525.

Best regards.

### CODE REVIEW

File: cmd/kubectl-gadget/utils/trace.go [hunk 1]
```diff
@@ -441,15 +442,16 @@ Loop:
 }
 
 // getTraceWatcher returns a watcher on trace(s) whom ID was given as parameter.
-// This watcher can then be used to wait on State.Output modification.
-func getTraceWatcher(traceID string) (watch.Interface, error) {
+// This watcher will wait from version resourceVersion (if set).
```
Comment (marga-kinvolk) [inline cmd/kubectl-gadget/utils/trace.go:445]: I'm not sure what you are trying to say here... What does "wait from version" mean? I think you might want to modify the other part of the sentence instead:

// getTraceWatcher returns a watcher on trace(s) for the received ID, 
// that have at least the received resourceVersion.
// This watcher can then be used to wait until the State.Output is modified.

File: cmd/kubectl-gadget/utils/trace.go [hunk 2]
```diff
@@ -465,13 +467,30 @@ func getTraceWatcher(traceID string) (watch.Interface, error) {
...
-	tracesNumber := 0
+	traceList, err := getTraceListFromID(traceID)
+	if err != nil {
+		return nil, err
+	}
+
+	tracesNumber := len(traceList.Items)
 	watchedTracesNumber := 0
 
+	minResourceVersion := 0
```
Comment (marga-kinvolk) [inline cmd/kubectl-gadget/utils/trace.go:478]: Can you add a comment explaining what this resourceVersion means in this context and why you need to look for the min value?

File: cmd/kubectl-gadget/utils/trace.go [hunk 3]
```diff
@@ -502,15 +527,6 @@ func waitForCondition(traceID string, conditionFunction func(*gadgetv1alpha1.Tra
 			return false, nil
 		}
```
[the remark this answers is not in the document]
Comment (eiffel-fl) [reply cmd/kubectl-gadget/utils/trace.go:540]: I totally rewrote it.
It should now tackle a lot of cases, even some particular obscure ones.

File: cmd/kubectl-gadget/utils/trace.go [hunk 4]
```diff
@@ -465,52 +468,77 @@ func getTraceWatcher(traceID string) (watch.Interface, error) {
...
 		return nil, err
 	}
 
 	nodeErrors := make(map[string]string)
 	nodeWarnings := make(map[string]string)
 
+	// We will only watch the traces which were not ready.
+	tracesToWatch := tracesNumber - tracesReady
+	watchedTracesNumber := 0
+
```
Comment (blanquicet) [inline cmd/kubectl-gadget/utils/trace.go:509]: As described in the comment above. If you do this, you have to discard the event coming from the already read trace. Otherwise, there is the risk that the same trace that is already ready make the watcher condition goes out and we do not wait for the other traces to be ready.

To solve this, I propose to create a map where you store for each trace its status (whether it satisfies the condition or not) and then you return only when all the traces are ready. What do you think?

File: cmd/kubectl-gadget/utils/trace.go [hunk 5]
```diff
@@ -465,52 +468,77 @@ func getTraceWatcher(traceID string) (watch.Interface, error) {
...
 
-		// Deal particularly with error.
-		if event.Type == watch.Error {
+		switch event.Type {
+		case watch.Deleted:
+			// If for some strange reasons (e.g. users deleted a trace during this
+			// operation) a trace is deleted, we need to take care of this by
+			// decrementing the tracesNumber.
+			// Otherwise we would still wait for the old number and we would timeout.
+			tracesNumber--
```
Comment (blanquicet) [inline cmd/kubectl-gadget/utils/trace.go:526]: Extreme case but possible 🙂. However, I think you should decrease `tracesToWatch` and we need to be sure we do not return it:

```suggestion
			tracesToWatch--
			// remove that trace from returnedTraces (in case it was already added)
```

**Review by blanquicet — DISMISSED** [review]
It is complex but I think we already have a good starting point. Thanks for working on this!

I tested and found a couple of problems. Let me know if you need further clarifications for my comments.

File: cmd/kubectl-gadget/utils/trace.go [hunk 6]
```diff
@@ -465,52 +468,77 @@ func getTraceWatcher(traceID string) (watch.Interface, error) {
...
+
+	tracesNumber := len(traceList.Items)
+	tracesReady := 0
+
+	// Maybe some traces are already ready?
+	for _, trace := range traceList.Items {
+		if conditionFunction(&trace) {
+			tracesReady++
+		}
+	}
```
[the remark this answers is not in the document]
Comment (eiffel-fl) [reply cmd/kubectl-gadget/utils/trace.go:484]: You are right, the logic is wrong here.
I wrote it a bite late and just figured out we can have some traces ready and some not instead of either all ready or none ready.

File: cmd/kubectl-gadget/utils/trace.go (hunk 5 above)
Comment (blanquicet) [reply cmd/kubectl-gadget/utils/trace.go:526]: I will try to test it later

File: cmd/kubectl-gadget/utils/trace.go (hunk 4 above)
Comment (eiffel-fl) [reply cmd/kubectl-gadget/utils/trace.go:509]: > As described in the comment above. If you do this, you have to discard the event coming from the already read trace. Otherwise, there is the risk that the same trace that is already ready make the watcher condition goes out and we do not wait for the other traces to be ready.

This should never happens due to using the list `ResourceVersion` (RV).
Indeed, by using this RV it would prevent receiving the events which modified the traces to be ready as those events belong to the past.

File: cmd/kubectl-gadget/utils/trace.go (hunk 5 above)
Comment (eiffel-fl) [reply cmd/kubectl-gadget/utils/trace.go:526]: Right, I added this variable at my last attempt yesterday and it seems everything is not really polished :sweat_smile:.

File: cmd/kubectl-gadget/utils/trace.go [hunk 7]
```diff
@@ -465,52 +468,77 @@ func getTraceWatcher(traceID string) (watch.Interface, error) {
...
-			// number of trace:
-			// To establish initial state, the watch begins with synthetic "Added"
-			// events of all resources instances that exist at the starting resource
-			// version
-			tracesNumber++
-		}
-
 		trace := event.Object.(*gadgetv1alpha1.Trace)
 
 		if trace.Status.OperationWarning != "" {
```
[the remark this answers is not in the document]
Comment (mauriciovasquezbernal) [reply cmd/kubectl-gadget/utils/trace.go:544]: > statement to explain why having a warning does not mean that trace can be considered as "watched" (i.e. watchedTracesNumber is not increased). 

`watchedTracesNumber` is actually increased there on L522. I just removed it to avoid counting it twice.

File: cmd/kubectl-gadget/utils/trace.go (hunk 4 above)
Comment (blanquicet) [reply cmd/kubectl-gadget/utils/trace.go:509]: The problem is that when the trace-controller manages an operation it modifies the trace twice: the first one to remove the operation from the trace annotations (generating one event on the CLI) and the second one to update the status with the new state or the output (generating another event). 

Therefore, if the event that modified the trace to be ready is the one for the change on the annotations, then the watcher will receive another event for the change in the status (this is the one that needs to be discarded). Similarly, if the trace is not ready when the watcher starts, it could receive two consecutive events from the same trace and wrongly decide that all traces are ready (again here, the second one needs to be discarded). BTW, I reproduced the second case.

That's why I propose to have a map to avoid increasing the `watchedTracesNumber` twice for the same trace. What do you think?

File: cmd/kubectl-gadget/utils/trace.go (hunk 5 above)
Comment (blanquicet) [reply cmd/kubectl-gadget/utils/trace.go:526]: No problem. I suggest you test it several times locally by using the flag Mauro added to avoid redeploying the IG every time:

```
$ # Deploy IG in a multi-node cluster
$ pwd
/path/to/source/code/of/inspektor-gadget
$ export KUBECTL_GADGET=/path/to/source/code/of/inspektor-gadget/kubectl-gadget
$ cd integration/
$ sudo -E go test -count=5 -run TestSeccompadvisor -tags withebpf -integration -no-deploy -test.v ./...
```

That's how I easily reproduced the two issues I reported in the previous comments.

File: cmd/kubectl-gadget/utils/trace.go (hunk 4 above)
Comment (eiffel-fl) [reply cmd/kubectl-gadget/utils/trace.go:509]: I see.
Actually the code would not handle if, for example, the same operation is called twice.
A simple counter does, sadly, not suffice.
I will add a map of traces we watched, if a trace is already watched, we would not watch it again.

File: cmd/kubectl-gadget/utils/trace.go (hunk 7 above)
[the remark this answers is not in the document]
Comment (blanquicet) [reply cmd/kubectl-gadget/utils/trace.go:544]: Absolutely! I missed it, sorry 😅

File: cmd/kubectl-gadget/utils/trace.go [hunk 8]
```diff
@@ -531,12 +575,9 @@ func waitForCondition(traceID string, conditionFunction func(*gadgetv1alpha1.Tra
 			return false, nil
```
Comment (mauriciovasquezbernal) [inline cmd/kubectl-gadget/utils/trace.go:575]: This can't return `false` here all the times, otherwise if all traces are in error it implies this code would time for sure. 

I think this block can be rewritten as:

```
		if trace.Status.OperationWarning != "" {
			// The trace can have a warning but satisfies conditionFunction.
			// So, we do not add it to the map here.
			nodeWarnings[trace.Spec.Node] = trace.Status.OperationWarning
		}

		if trace.Status.OperationError != "" {
			nodeErrors[trace.Spec.Node] = trace.Status.OperationError
		}

		// If the trace does not satisfy the condition function, we are not
		// interested.
		if trace.Status.OperationError == "" && !conditionFunction(trace) {
			return false, nil
		}

		watchedTraces[trace.ObjectMeta.Name] = *trace

		return len(watchedTraces) == tracesToWatch, nil
```

File: cmd/kubectl-gadget/utils/trace.go [hunk 9]
```diff
@@ -552,6 +593,10 @@ func waitForCondition(traceID string, conditionFunction func(*gadgetv1alpha1.Tra
 		return nil, err
 	}
 
+	for _, trace := range watchedTraces {
+		returnedTraces.Items = append(returnedTraces.Items, trace)
+	}
```
Comment (mauriciovasquezbernal) [inline cmd/kubectl-gadget/utils/trace.go:598]: This should be done before L588 to print warnings.

File: cmd/kubectl-gadget/utils/trace.go [hunk 10]
```diff
@@ -464,61 +467,102 @@ func getTraceWatcher(traceID string) (watch.Interface, error) {
...
+	tracesSatisfied := 0
 
-	tracesNumber := 0
-	watchedTracesNumber := 0
+	// Maybe some traces already satisfy conditionFunction?
+	for _, trace := range traceList.Items {
+		if conditionFunction(&trace) {
+			tracesSatisfied++
+			watchedTraces[trace.ObjectMeta.Name] = trace
+		}
```
Comment (mauriciovasquezbernal) [inline cmd/kubectl-gadget/utils/trace.go:485]: Handling of operation warning an error is missing here.

File: cmd/kubectl-gadget/utils/trace.go [hunk 11]
```diff
@@ -464,61 +467,102 @@ func getTraceWatcher(traceID string) (watch.Interface, error) {
...
+
+	// If they all satisify conditionFunction we can quit now without having to
+	// watch events.
+	if tracesSatisfied == tracesNumber {
+		for _, trace := range watchedTraces {
+			returnedTraces.Items = append(returnedTraces.Items, trace)
+		}
+
+		return &returnedTraces, nil
+	}
```
Comment (mauriciovasquezbernal) [inline cmd/kubectl-gadget/utils/trace.go:496]: This will miss printing warnings and errors.

File: cmd/kubectl-gadget/utils/trace.go [hunk 12]
```diff
@@ -464,61 +467,102 @@ func getTraceWatcher(traceID string) (watch.Interface, error) {
...
-
 		if trace.Status.OperationWarning != "" {
+			// The trace can have a warning but satisfies conditionFunction.
+			// So, we do not add it to the map here.
 			nodeWarnings[trace.Spec.Node] = trace.Status.OperationWarning
 		}
 
 		if trace.Status.OperationError != "" {
-			watchedTracesNumber++
+			watchedTraces[trace.ObjectMeta.Name] = *trace
```
Comment (mauriciovasquezbernal) [inline cmd/kubectl-gadget/utils/trace.go:565]: Does it mean we can return traces with errors?

**Review by mauriciovasquezbernal — COMMENTED** [review]
I think it's a good improvement but there are few things that need to be fixed up. The OperationError handling is causing some pain IMO. I have an idea to implement it, but it's too long to explain with words, let me paste the code here. WDYT?

Note this code is missing the handling of the some comments I made above. 

```go
// waitForCondition waits for the traces with the ID received as parameter to
// satisfy the conditionFunction received as parameter.
func waitForCondition(traceID string, conditionFunction func(*gadgetv1alpha1.Trace) bool) (*gadgetv1alpha1.TraceList, error) {
	var returnedTraces gadgetv1alpha1.TraceList
	watchedTraces := make(map[string]gadgetv1alpha1.Trace)
	nodeErrors := make(map[string]string)
	nodeWarnings := make(map[string]string)

	traceList, err := getTraceListFromID(traceID)
	if err != nil {
		return nil, err
	}

	tracesNumber := len(traceList.Items)
	tracesSatisfied := 0

	// Initialize state with existing traces
	for _, trace := range traceList.Items {
		if trace.Status.OperationWarning != "" {
			// The trace can have a warning but satisfies conditionFunction.
			// So, we do not add it to the map here.
			nodeWarnings[trace.Spec.Node] = trace.Status.OperationWarning
		}

		if trace.Status.OperationError != "" {
			nodeErrors[trace.Spec.Node] = trace.Status.OperationError
		}

		if trace.Status.OperationError == "" && !conditionFunction(&trace) {
			continue
		}

		tracesSatisfied++
		watchedTraces[trace.ObjectMeta.Name] = trace
	}

	// If there are missing traces to be satisfied, start a watcher
	tracesToWatch := tracesNumber - tracesSatisfied
	if tracesToWatch > 0 {
		// Otherwise, we will need to watch events on them.
		// For this, we will get a watcher on all the traces which share the same ID.
		// Get a watcher on all the traces which have the same ID.
		// Indeed, all the traces on different nodes but linked to one gadget share
		// the same ID.
		// We will also begin to monitor events since the above GET of the traces
		// list.
		watcher, err := getTraceWatcher(traceID, traceList.ListMeta.ResourceVersion)
		if err != nil {
			return nil, err
		}

		ctx, cancel := watchtools.ContextWithOptionalTimeout(context.Background(), traceTimeout)
		_, err = untilWithoutRetry(ctx, watcher, func(event watch.Event) (bool, error) {
			// This function will be executed until:
			// 1. The number of watched traces equals the number of traces to watch,
			// i.e. we dealt with the traces which interest us.
			// 2. Or it returns an error.
			// 3. Or time out is fired.
			// NOTE In case 2 and 3, it exists, at least, one trace we did not deal
			// with.
			trace := event.Object.(*gadgetv1alpha1.Trace)

			// If the trace is already in the map, it means it already satisfies
			// conditionFunction, so we can skip this event.
			if _, present := watchedTraces[trace.ObjectMeta.Name]; present {
				return false, nil
			}

			switch event.Type {
			case watch.Deleted:
				// If for some strange reasons (e.g. users deleted a trace during this
				// operation) a trace is deleted, we need to take care of this by
				// decrementing the tracesToWatch.
				// Otherwise we would still wait for the old number and we would timeout.
				tracesToWatch--

				// We also remove it from the map to avoid returning a deleted trace.
				delete(watchedTraces, trace.ObjectMeta.Name)
			case watch.Modified:
				// We will deal with this type of event below
			case watch.Error:
				// Deal particularly with error.
				return false, err
			case watch.Added:
				// createTraces() creates traces synchronously.
				// So, if a watch.Added event occurs it means there is a problem (e.g. the
				// user creates a trace by snooping on the traceID of existing traces).
				return false, fmt.Errorf("No traces with the given traceID (%s) should be created", traceID)
			default:
				// We are not interested in other event types.
				return false, nil
			}

			if trace.Status.OperationWarning != "" {
				// The trace can have a warning but satisfies conditionFunction.
				// So, we do not add it to the map here.
				nodeWarnings[trace.Spec.Node] = trace.Status.OperationWarning
			}

			if trace.Status.OperationError != "" {
				nodeErrors[trace.Spec.Node] = trace.Status.OperationError
			}

			// If the trace does not satisfy the condition function, we are not
			// interested.
			if trace.Status.OperationError == "" && !conditionFunction(trace) {
				return false, nil
			}

			watchedTraces[trace.ObjectMeta.Name] = *trace

			return len(watchedTraces) == tracesToWatch, nil
		})
		cancel()
		if err != nil {
			return nil, err
		}
	}

	for _, trace := range watchedTraces {
		returnedTraces.Items = append(returnedTraces.Items, trace)
	}

	// We print warnings only if all trace failed.
	if len(returnedTraces.Items) == 0 {
		printTraceFeedback(nodeWarnings, tracesNumber)
	}

	// We print errors whatever happened.
	printTraceFeedback(nodeErrors, tracesNumber)

	return &returnedTraces, nil
}
```

File: cmd/kubectl-gadget/utils/trace.go [hunk 13]
```diff
@@ -464,61 +467,102 @@ func getTraceWatcher(traceID string) (watch.Interface, error) {
...
 		// This function will be executed until:
-		// 1. The number of watched traces equals the number of traces, i.e. we
-		// dealt with the traces which interest us.
+		// 1. The number of watched traces equals the number of traces to watch,
+		// i.e. we dealt with the traces which interest us.
 		// 2. Or it returns an error.
 		// 3. Or time out is fired.
 		// NOTE In case 2 and 3, it exists, at least, one trace we did not deal
 		// with.
+		trace := event.Object.(*gadgetv1alpha1.Trace)
```
[the remark this answers is not in the document]
Comment (eiffel-fl) [reply cmd/kubectl-gadget/utils/trace.go:525]: I did this in a previous version of the code but I do not think this is necessary because the watcher only watches for this type of object.
I will nonetheless add it back, I rather have useless branch than panic.

File: cmd/kubectl-gadget/utils/trace.go [hunk 14]
```diff
@@ -464,61 +467,102 @@ func getTraceWatcher(traceID string) (watch.Interface, error) {
...
+		switch event.Type {
+		case watch.Deleted:
+			// If for some strange reasons (e.g. users deleted a trace during this
+			// operation) a trace is deleted, we need to take care of this by
+			// decrementing the tracesToWatch.
+			// Otherwise we would still wait for the old number and we would timeout.
+			tracesToWatch--
+
+			// We also remove it from the map to avoid returning a deleted trace.
+			delete(watchedTraces, trace.ObjectMeta.Name)
```
[the remark this answers is not in the document]
Comment (eiffel-fl) [reply cmd/kubectl-gadget/utils/trace.go:542]: I do not think there is a silver bullet.
If the user deleted a trace, I would be OK to do an error (you are looking for troubles then get some troubles).
But what happens if a node crashes? Is the traces on it deleted? If so, what do we want to do? Continue with the existing traces/nodes or return an error which can inform the user something wrong happened on a node?

File: cmd/kubectl-gadget/utils/trace.go (hunk 12 above)
Comment (eiffel-fl) [reply cmd/kubectl-gadget/utils/trace.go:565]: It seems...
I will filter during the gather loop at the end of the function.

Comment (eiffel-fl) [reply cmd/kubectl-gadget/utils/trace.go:565]: It seems...
I will filter during the gather loop at the end of the function.

**Comment by eiffel-fl** [comment]
Thank you for your suggestion and review.
When I wrote the last version of it I really did not like to have to first deal with the already existing traces then do the exact same code in the event loop.
I will try to factorize this.

File: cmd/kubectl-gadget/utils/trace.go (hunk 12 above)
Comment (eiffel-fl) [reply cmd/kubectl-gadget/utils/trace.go:565]: Thinking to it I am not sure what is the good behavior here.
Like the above question, we can either return with the succeeded traces or we can decide to timeout on purpose because one trace is in error and does not satisfy `conditionFunction()`.

Comment (blanquicet) [reply cmd/kubectl-gadget/utils/trace.go]: IMO, we should not time out if there are traces that returned an error but `waitForCondition()` should return **only** successful traces. 

I think we can follow Mauro's suggestion [here](https://github.com/kinvolk/inspektor-gadget/pull/535#discussion_r815025457) and then filter out the traces with error.

Comment (eiffel-fl) [reply cmd/kubectl-gadget/utils/trace.go]: I changed the thing a little bit.
There are one map for traces which satisfy the `conditionFunction()` and another for traces which have `trace.Status.Operationerror != ""`.

File: cmd/kubectl-gadget/utils/trace.go (hunk 13 above)
[the remark this answers is not in the document]
Comment (mauriciovasquezbernal) [reply cmd/kubectl-gadget/utils/trace.go]: What you said is almost right except for the `watch.Error` that would cause a panic.

File: cmd/kubectl-gadget/utils/trace.go (hunk 14 above)
[the remark this answers is not in the document]
Comment (mauriciovasquezbernal) [reply cmd/kubectl-gadget/utils/trace.go]: I understand your point, I'm fine with handling this case but I think we should concentrate on the ones that are more common to be sure they work fine.

File: cmd/kubectl-gadget/utils/trace.go [hunk 15]
```diff
@@ -452,97 +463,175 @@ func getTraceWatcher(traceID string) (watch.Interface, error) {
...
+		})
+		cancel()
+	}
+
+	for _, trace := range erroredTraces {
+		nodeErrors[trace.Spec.Node] = trace.Status.OperationError
+	}
 
 	// We print errors whatever happened.
 	defer printTraceFeedback(nodeErrors, tracesNumber)
```
Comment (mauriciovasquezbernal) [inline cmd/kubectl-gadget/utils/trace.go:596]: It can be done without defer.

File: cmd/kubectl-gadget/utils/trace.go [hunk 16]
```diff
@@ -463,95 +466,157 @@ func getTraceWatcher(traceID string) (watch.Interface, error) {
...
-	defer printTraceFeedback(nodeErrors, tracesNumber)
+	printTraceFeedback(nodeErrors, tracesNumber)
 
 	// We print warnings only if all trace failed.
-	if len(returnedTraces.Items) == 0 {
+	if len(satisfiedTraces) == 0 {
 		printTraceFeedback(nodeWarnings, tracesNumber)
 	}
 
 	if err != nil {
```
Comment (eiffel-fl) [inline cmd/kubectl-gadget/utils/trace.go:612]: `err` is not the good one.

File: cmd/kubectl-gadget/utils/trace.go [hunk 17]
```diff
@@ -463,95 +466,157 @@ func getTraceWatcher(traceID string) (watch.Interface, error) {
...
+				// operation) a trace is deleted, we need to take care of this by
+				// decrementing the tracesToWatch.
+				// Otherwise we would still wait for the old number and we would
+				// timeout.
+				tracesToWatch--
+
+				trace, ok := event.Object.(*gadgetv1alpha1.Trace)
+				if !ok {
+					return false, fmt.Errorf("Received object cannot be cast to Trace: %v", event.Object)
+				}
```
Comment (mauriciovasquezbernal) [inline cmd/kubectl-gadget/utils/trace.go:540]: Actually in this case the type assertion is not needed as you already checked event.Type and we're sure that for deleted events the object is a trace.

File: cmd/kubectl-gadget/utils/trace.go [hunk 18]
```diff
@@ -463,95 +466,157 @@ func getTraceWatcher(traceID string) (watch.Interface, error) {
...
+				// We are not interested in other event types.
+				return false, nil
+			}
 
-			return false, nil
-		}
+			trace, ok := event.Object.(*gadgetv1alpha1.Trace)
+			if !ok {
+				return false, fmt.Errorf("Received object cannot be cast to Trace: %v", event.Object)
+			}
```
Comment (mauriciovasquezbernal) [inline cmd/kubectl-gadget/utils/trace.go:569]: same here, this only be executed for `watch.Modified` so the assertion is not required here.

File: cmd/kubectl-gadget/utils/trace.go [hunk 19]
```diff
@@ -463,95 +466,157 @@ func getTraceWatcher(traceID string) (watch.Interface, error) {
...
-		returnedTraces.Items = append(returnedTraces.Items, *trace)
+			if trace.Status.OperationError != "" {
+				erroredTraces[trace.ObjectMeta.Name] = trace
 
-		return watchedTracesNumber == tracesNumber, nil
-	})
-	cancel()
+				// If the trace satisfied the function, we do not care now because it
+				// has an error.
+				delete(satisfiedTraces, trace.ObjectMeta.Name)
```
Comment (mauriciovasquezbernal) [inline cmd/kubectl-gadget/utils/trace.go:582]: is this something that can actually happen?

File: cmd/kubectl-gadget/utils/trace.go [hunk 20]
```diff
@@ -463,95 +466,157 @@ func getTraceWatcher(traceID string) (watch.Interface, error) {
...
+
+			// If the trace does not satisfy the condition function, we are not
+			// interested.
+			if !conditionFunction(trace) {
+				return false, nil
+			}
+
+			satisfiedTraces[trace.ObjectMeta.Name] = trace
+
+			return len(satisfiedTraces)+len(erroredTraces) == tracesToWatch, nil
```
Comment (mauriciovasquezbernal) [inline cmd/kubectl-gadget/utils/trace.go:595]: Shouldn't it be `len(satisfiedTraces)+len(erroredTraces) == tracesNumber` ? (`satisfiedTraces` and `erroredTraces` can be filled with traces before the watch operation).

File: cmd/kubectl-gadget/utils/trace.go (hunk 16 above)
Comment (mauriciovasquezbernal) [reply cmd/kubectl-gadget/utils/trace.go:612]: Why not?

File: cmd/kubectl-gadget/utils/trace.go [hunk 21]
```diff
@@ -463,95 +466,157 @@ func getTraceWatcher(traceID string) (watch.Interface, error) {
...
+				erroredTraces[trace.ObjectMeta.Name] = trace
 
-		return watchedTracesNumber == tracesNumber, nil
-	})
-	cancel()
+				// If the trace satisfied the function, we do not care now because it
+				// has an error.
+				delete(satisfiedTraces, trace.ObjectMeta.Name)
+
+				return false, nil
```
Comment (mauriciovasquezbernal) [inline cmd/kubectl-gadget/utils/trace.go:584]: Why to always return false? I think it should return the same as in line 595.

File: cmd/kubectl-gadget/utils/trace.go [hunk 22]
```diff
@@ -463,95 +466,157 @@ func getTraceWatcher(traceID string) (watch.Interface, error) {
...
-		trace := event.Object.(*gadgetv1alpha1.Trace)
+		satisfiedTraces[trace.ObjectMeta.Name] = &traceList.Items[i]
+	}
 
-		if trace.Status.OperationWarning != "" {
-			nodeWarnings[trace.Spec.Node] = trace.Status.OperationWarning
+	tracesNumber := len(traceList.Items)
+
+	// We only watch the traces which did not satisfy conditionFunction.
+	tracesToWatch := tracesNumber - len(satisfiedTraces)
```
[the remark this answers is not in the document]
Comment (mauriciovasquezbernal) [reply cmd/kubectl-gadget/utils/trace.go:504]: also, do we really need this `tracesToWatch` variable? I think it complicates the logic and we can do all the calculations without introducing a new one.

File: cmd/kubectl-gadget/utils/trace.go (hunk 16 above)
Comment (eiffel-fl) [reply cmd/kubectl-gadget/utils/trace.go:612]: I wrote this comment to remind me to check this behavior.
But in the `watch`, `err` value is just changed and it nos declared again.
So, it is fine to use it here.

File: cmd/kubectl-gadget/utils/trace.go (hunk 21 above)
Comment (eiffel-fl) [reply cmd/kubectl-gadget/utils/trace.go:584]: Good catch!

File: cmd/kubectl-gadget/utils/trace.go (hunk 19 above)
Comment (mauriciovasquezbernal) [reply cmd/kubectl-gadget/utils/trace.go:575]: But it's under the operation error conditional, can a trace that satisfied the condition go into error?

Comment (blanquicet) [reply cmd/kubectl-gadget/utils/trace.go:575]: IMO, it cannot happen and this operation should be removed.

File: cmd/kubectl-gadget/utils/trace.go (hunk 16 above)
Comment (blanquicet) [reply cmd/kubectl-gadget/utils/trace.go:605]: `err` is wrongly being redeclared [here](https://github.com/kinvolk/inspektor-gadget/blob/e6ff7773f65674691ff850a02401f01f9633effb/cmd/kubectl-gadget/utils/trace.go#L514) so this error check is useless right now. I think that by reusing the same outer `err` variable, the logic is correct.

**Review by blanquicet — COMMENTED** [review]
I added comments on some already opened discussions. I will run another test session tomorrow after those discussions are closed.

File: cmd/kubectl-gadget/utils/trace.go (hunk 16 above)
Comment (eiffel-fl) [reply cmd/kubectl-gadget/utils/trace.go:605]: > err is wrongly being redeclared [here](https://github.com/kinvolk/inspektor-gadget/blob/e6ff7773f65674691ff850a02401f01f9633effb/cmd/kubectl-gadget/utils/trace.go#L514) so this error check is useless right now. I think that by reusing the same [outer err variable](https://github.com/kinvolk/inspektor-gadget/blob/e6ff7773f65674691ff850a02401f01f9633effb/cmd/kubectl-gadget/utils/trace.go#L475), the logic is correct.

I do not think it is redeclared, `watcher` is declared here but `err` should be the one already declared above.
So, I think the actual logic is OK.
Otherwise, I will make it clearer defining `extError` and `innerError`.

Comment (blanquicet) [reply cmd/kubectl-gadget/utils/trace.go:605]: > I do not think it is redeclared, `watcher` is declared here but `err` should be the one already declared above.
>
As far as I know, if both [[1](https://github.com/kinvolk/inspektor-gadget/blob/032015089c5001c2ecaa58040a353421983bf54b/cmd/kubectl-gadget/utils/trace.go#L475)] and [[2]](https://github.com/kinvolk/inspektor-gadget/blob/032015089c5001c2ecaa58040a353421983bf54b/cmd/kubectl-gadget/utils/trace.go#L514)  were in the same block, then what you are saying would be true. Example [here](https://go.dev/play/p/HV_sDKtSK6O). Ref: https://go.dev/ref/spec#Short_variable_declarations.

However, given that they are within different blocks, it means that inner `err` is a new variable and not a redeclaration. Example [here](https://go.dev/play/p/NCSLdgITUXr). 

Or what did I miss/misunderstand?

Comment (eiffel-fl) [reply cmd/kubectl-gadget/utils/trace.go:605]: > Or what did I miss/misunderstand?

Nothing, this pattern is just particularly unclear and I will then make it clearer by adding two differently named variables.

Comment (blanquicet) [reply cmd/kubectl-gadget/utils/trace.go]: IMHO, having two error variables makes things even more complex 😅 .

I think it is enough to first declare the watcher and user `=` instead of `:=` when calling `getTraceWatcher()`. In that way, you are sure it is using the same outer `err` variable: 

```
		var watcher watch.Interface
		watcher, err = getTraceWatcher(traceID, traceList.ListMeta.ResourceVersion)		
```

Comment (mauriciovasquezbernal) [reply cmd/kubectl-gadget/utils/trace.go]: I agree that having two error variables is even more complicated.

**Review by mauriciovasquezbernal — APPROVED** [review]
I think it's good to go. (besides the inner/outer errors thing).

File: cmd/kubectl-gadget/utils/trace.go [hunk 23]
```diff
@@ -463,93 +466,150 @@ func getTraceWatcher(traceID string) (watch.Interface, error) {
...
-			// version
-			tracesNumber++
+		satisfiedTraces[trace.ObjectMeta.Name] = &traceList.Items[i]
+	}
+
+	tracesNumber := len(traceList.Items)
+
+	// We only watch the traces if there are some which did not already satisfy
+	// the conditionFunction.
+	if len(satisfiedTraces)+len(erroredTraces) != tracesNumber {
```
[the remark this answers is not in the document]
Comment (eiffel-fl) [reply cmd/kubectl-gadget/utils/trace.go:507]: Good catch, protect against trace creation after getting the number of them.

**Comment by eiffel-fl** [comment]
Thank you a lot for your thorough reviews!
Let's :crossed_fingers: the new code will catch all cases and we will not have to deal with it in 3 months.
